# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", "bower_components"]
port:             9001

# Custom vars
current_version:  1.1.1
repo:             https://github.com/jbrad/bootstrap-ios7

download_source:  https://github.com/jbrad/bootstrap-ios7/archive/v1.1.1.zip
download_dist:    https://github.com/jbrad/bootstrap-ios7/releases/download/v1.0.0/bootstrap-1.1.1-dist.zip

blog:             http://jasonbradley.me
expo:             http://jasonbradley.me

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js
