# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

# Custom vars
current_version:  2.0.0
repo:             https://github.com/jbrad/bootstrap-ios7
sass_repo:        https://github.com/jbrad/bootstrap-ios7

download:
  source:         https://github.com/jbrad/bootstrap-ios7/archive/v2.0.0.zip
  dist:           https://github.com/jbrad/bootstrap-ios7/releases/download/v2.0.0/bootstrap-2.0.0-dist.zip
  sass:           https://github.com/jbrad/bootstrap-ios7/archive/v2.0.0.tar.gz

blog:             http://jasonbradley.me